### PR TITLE
update quic-go to v0.14.0

### PR DESCRIPTION
**Pull request by marten-seemann**

### CODE REVIEW

**Comment by marten-seemann** [comment]
Yes, and it's bumping the version number, so this won't break any connections.

**Comment by Stebalien** [comment]
> Yes, and it's bumping the version number, so this won't break any connections.

But will old nodes be able to talk to new nodes?

**Comment by marten-seemann** [comment]
No, we don't have any backwards compatibility. This is the reason why it's still experimental.

**Comment by Stebalien** [comment]
Got it.

I'd like to release _a_ stable QUIC version ASAP, even if it's not the final RFC. We need QUIC and I don't want to keep waiting on the IETF.

However, when we do this, we'll need to support it into the future (i.e., support multiple versions). Is there any reason not to pick draft 24?

**Comment by marten-seemann** [comment]
> However, when we do this, we'll need to support it into the future (i.e., support multiple versions). Is there any reason not to pick draft 24?

draft-25 will be the draft version that's intended for deployment by the IETF working group. There are a couple of important changes between -24 and -25, and it would be hard to support both at the same time. I suggest we wait for -25 before making QUIC the default transport.

**Comment by Stebalien** [comment]
Got it. Any idea when draft 25 likely to be finalized?

**Comment by marten-seemann** [comment]
I assume it will ship before the next QUIC working group interim meeting end of January next year.

**Comment by Stebalien** [comment]
Awesome!

**Comment by Stebalien** [comment]
@marten-seemann tell me when you've merged this so I can bubble it to go-ipfs. I'd like to get it into the release.

**Pull request closed without merging**
