### PR TITLE
Added support of ED25519 keys

### PR DESCRIPTION
**Pull request by xaionaro**
Works only with Go>=1.13

### CODE REVIEW

**Comment by xaionaro** [comment]
The test fails because of Go1.12. It's required to use Go1.13

**Comment by marten-seemann** [comment]
As noted in https://github.com/libp2p/go-libp2p-quic-transport/issues/60#issuecomment-507524509, the better way to add ed25519 support is by reusing the code from the TLS package.

**Comment by xaionaro** [comment]
@marten-seemann if you mean that this PR should be rejected because there's another task to reuse code from TLS package then I humbly disagree:

This tasks are two separate tasks which are not blocking each other. We can add support of ED25519 to the current code and while another task in someday after that we can declare current code obsolete and replace it by a new one (which will reuse the TLS package code).

This PR just improves the old code and allows people like me to use UDP with ED25519 right now (or right after official release of Go1.13). That's all.

**Comment by marten-seemann** [comment]
@xaionaro We can't merge this PR at this time, since Go 1.13 is not released anyway. So it will be blocked for at least another 6 weeks. Furthermore, even after the release of Go 1.13 we have to worry about backwards compatibility: Nodes that haven't updated to a libp2p release compiled with Go 1.13 won't be able to complete handshake.

**Comment by xaionaro** [comment]
> @xaionaro We can't merge this PR at this time, since Go 1.13 is not released anyway. So it will be blocked for at least another 6 weeks.

Yes, I understand that. But it at least has a more-less specific date. And it's not that far away from now.

> Furthermore, even after the release of Go 1.13 we have to worry about backwards compatibility: Nodes that haven't updated to a libp2p release compiled with Go 1.13 won't be able to complete handshake.

As I see IPFS already depends on Go1.12 which is currently the latest version. So in my understanding when Go1.13 will be released then IPFS will migrate on it anyway.

**Comment by marten-seemann** [comment]
#67 is the way to go.

**Pull request closed without merging**
