### PR TITLE
add SetQUICConfig function

### PR DESCRIPTION
**Pull request by ansoda**

### CODE REVIEW

**Review by marten-seemann — COMMENTED** [review]
1. What would that be needed for?
2. This implementation won't work. It's racy.

**Comment by ansoda** [comment]
I want to change the default MaxIdleTimeout config

**Comment by marten-seemann** [comment]
Why?

**Comment by ansoda** [comment]
Our system is in a weak network environment, I want to judge whether I have been disconnected as soon as possible, and reconnect as soon as possible.

**Comment by marten-seemann** [comment]
> I want to judge whether I have been disconnected as soon as possible, and reconnect as soon as possible.

How would a shorter idle timeout help you? QUIC already does keep-alives. Disconnecting and re-connecting would just mean throwing away valuable congestion control state (like RTT measurements).

**Comment by ansoda** [comment]
How often does KeepAlive send a heartbeat check? Thank you.

**Comment by marten-seemann** [comment]
Every half the idle timeout.

**Comment by ansoda** [comment]
Ok, thank you. Let me think about how to make our system recover quickly in the weak wifi network.

**Pull request closed without merging**
